networks:
  default:

volumes:
  mysql-data:

services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../.:/var/www/html:delegated
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: development.Dockerfile
    volumes:
      - ../.:/var/www/html:delegated
    depends_on:
      - mysql
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE-off}"
      XDEBUG_CONFIG: 'start_with_request=yes client_host=${XDEBUG_CONFIG_CLIENT_HOST-} idekey=${XDEBUG_CONFIG_IDEKEY-}'

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root

  node:
    image: node:20-alpine
    working_dir: /var/www/html
    volumes:
      - ../.:/var/www/html:delegated
